=== consortium-chat/constitution/tome.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema
  xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:tome="https://consortium.chat/tome"
  targetNamespace="https://consortium.chat/tome"
  elementFormDefault="qualified"
  version="1.1">

  <!-- Root element -->
  <element
    name="tome"
    type="tome:tomeType" />

  <!-- Container base -->
  <complexType name="container">
    <sequence>
      <element
        name="title"
        type="tome:titleType" />
      <choice
        minOccurs="0"
        maxOccurs="unbounded">
        <element
          name="text"
          type="tome:textType" />
        <element
          name="list"
          type="tome:listType" />
        <element
          name="reference"
          type="tome:referenceType" />
      </choice>
    </sequence>
    <attribute
      name="id"
      type="tome:idType"
      use="required" />
  </complexType>

  <!-- Tier 1 Container -->
  <complexType name="tomeType">
    <sequence>
      <element
        name="title"
        type="tome:titleType" />
      <element
        name="chapter"
        type="tome:chapterType"
        minOccurs="0"
        maxOccurs="unbounded">
        <unique name="blarg">
          <selector xpath="./*" />
          <field xpath="@id" />
        </unique>
      </element>
    </sequence>
    <attribute
      name="id"
      type="tome:idType"
      use="required" />
  </complexType>

  <!-- Tier 2 Container -->
  <complexType name="chapterType">
    <complexContent>
      <extension base="tome:container">
        <sequence>
          <element
            name="section"
            type="tome:sectionType"
            minOccurs="0"
            maxOccurs="unbounded" />
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <!-- Tier 3+ Container -->
  <complexType name="sectionType">
    <complexContent>
      <extension base="tome:container">
        <sequence>
          <element
            name="section"
            type="tome:sectionType"
            minOccurs="0"
            maxOccurs="unbounded" />
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <!-- Text without id -->
  <complexType
    name="noidTextType"
    mixed="true">
    <choice
      minOccurs="0"
      maxOccurs="unbounded">
      <element
        name="inlist"
        type="tome:inlistType" />
      <element
        name="toa"
        type="tome:toaType" />
    </choice>
  </complexType>

  <!-- Text base -->
  <complexType
    name="textType"
    mixed="true">
    <choice
      minOccurs="0"
      maxOccurs="unbounded">
      <element
        name="inlist"
        type="tome:inlistType" />
      <element
        name="toa"
        type="tome:toaType" />
    </choice>
    <attribute
      name="id"
      type="tome:idType"
      use="required" />
  </complexType>

  <!-- Term of Art declaration -->
  <complexType name="toaType" mixed="true">
    <attribute
      name="definition"
      type="boolean"
      default="false"
      use="optional" />
    <attribute
      name="ref"
      type="string"
      use="required" />
  </complexType>

  <!-- Inline list declaration -->
  <complexType name="inlistType">
    <sequence>
      <element
        name="item"
        type="tome:noidTextType"
        minOccurs="1"
        maxOccurs="unbounded" />
    </sequence>
    <attribute
      name="join"
      type="tome:conjunction"
      use="optional" />
  </complexType>

  <!-- List declaration -->
  <complexType name="listType">
    <sequence>
      <element
        name="intro"
        type="tome:noidTextType"
        minOccurs="0"
        maxOccurs="1" />
      <element
        name="item"
        type="tome:textType"
        minOccurs="1"
        maxOccurs="unbounded" />
    </sequence>
    <attribute
      name="id"
      type="tome:idType"
      use="required" />
    <attribute
      name="join"
      type="tome:conjunction"
      use="optional" />
  </complexType>

  <!-- Container title -->
  <simpleType name="titleType">
    <restriction base="token" />
  </simpleType>

  <!-- External tome reference -->
  <simpleType name="referenceType">
    <list itemType="tome:idType" />
  </simpleType>

  <!-- Conjunction -->
  <simpleType name="conjunction">
    <restriction base="string">
      <enumeration value="and" />
      <enumeration value="or" />
      <enumeration value="andor" />
    </restriction>
  </simpleType>

  <!-- Identifier -->
  <simpleType name="idType">
    <restriction base="string">
      <pattern value="#️⃣|\*️⃣|0️⃣|1️⃣|2️⃣|3️⃣|4️⃣|5️⃣|6️⃣|7️⃣|8️⃣|9️⃣|©️|®️|‼️|⁉️|™️|ℹ️|↔️|↕️|↖️|↗️|↘️|↙️|↩️|↪️|⌚️|⌛️|⌨️|⏏️|⏩️|⏪️|⏫️|⏬️|⏭️|⏮️|⏯️|⏰️|⏱️|⏲️|⏳️|⏸️|⏹️|⏺️|Ⓜ️|▪️|▫️|▶️|◀️|◻️|◼️|◽️|◾️|☀️|☁️|☂️|☃️|☄️|☎️|☑️|☔️|☕️|☘️|☝️|☠️|☢️|☣️|☦️|☪️|☮️|☯️|☸️|☹️|☺️|♀️|♂️|♈️|♉️|♊️|♋️|♌️|♍️|♎️|♏️|♐️|♑️|♒️|♓️|♠️|♣️|♥️|♦️|♨️|♻️|♾️|♿️|⚒️|⚓️|⚔️|⚕️|⚖️|⚗️|⚙️|⚛️|⚜️|⚠️|⚡️|⚧️|⚪️|⚫️|⚰️|⚱️|⚽️|⚾️|⛄️|⛅️|⛈️|⛎️|⛏️|⛑️|⛓️|⛔️|⛩️|⛪️|⛰️|⛱️|⛲️|⛳️|⛴️|⛵️|⛷️|⛸️|⛹️|⛺️|⛽️|✂️|✅️|✈️|✉️|✊️|✋️|✌️|✍️|✏️|✒️|✔️|✖️|✝️|✡️|✨️|✳️|✴️|❄️|❇️|❌️|❎️|❓️|❔️|❕️|❗️|❣️|❤️|➕️|➖️|➗️|➡️|➰️|➿️|⤴️|⤵️|⬅️|⬆️|⬇️|⬛️|⬜️|⭐️|⭕️|〰️|〽️|㊗️|㊙️|🀄|🃏|🅰️|🅱️|🅾️|🅿️|🆎|🆑|🆒|🆓|🆔|🆕|🆖|🆗|🆘|🆙|🆚|🈁|🈂️|🈚|🈯|🈲|🈳|🈴|🈵|🈶|🈷️|🈸|🈹|🈺|🉐|🉑|🌀|🌁|🌂|🌃|🌄|🌅|🌆|🌇|🌈|🌉|🌊|🌋|🌌|🌍|🌎|🌏|🌐|🌑|🌒|🌓|🌔|🌕|🌖|🌗|🌘|🌙|🌚|🌛|🌜|🌝|🌞|🌟|🌠|🌡️|🌤️|🌥️|🌦️|🌧️|🌨️|🌩️|🌪️|🌫️|🌬️|🌭|🌮|🌯|🌰|🌱|🌲|🌳|🌴|🌵|🌶️|🌷|🌸|🌹|🌺|🌻|🌼|🌽|🌾|🌿|🍀|🍁|🍂|🍃|🍄|🍅|🍆|🍇|🍈|🍉|🍊|🍋|🍌|🍍|🍎|🍏|🍐|🍑|🍒|🍓|🍔|🍕|🍖|🍗|🍘|🍙|🍚|🍛|🍜|🍝|🍞|🍟|🍠|🍡|🍢|🍣|🍤|🍥|🍦|🍧|🍨|🍩|🍪|🍫|🍬|🍭|🍮|🍯|🍰|🍱|🍲|🍳|🍴|🍵|🍶|🍷|🍸|🍹|🍺|🍻|🍼|🍽️|🍾|🍿|🎀|🎁|🎂|🎃|🎄|🎅|🎆|🎇|🎈|🎉|🎊|🎋|🎌|🎍|🎎|🎏|🎐|🎑|🎒|🎓|🎖️|🎗️|🎙️|🎚️|🎛️|🎞️|🎟️|🎠|🎡|🎢|🎣|🎤|🎥|🎦|🎧|🎨|🎩|🎪|🎫|🎬|🎭|🎮|🎯|🎰|🎱|🎲|🎳|🎴|🎵|🎶|🎷|🎸|🎹|🎺|🎻|🎼|🎽|🎾|🎿|🏀|🏁|🏂|🏃|🏄|🏅|🏆|🏇|🏈|🏉|🏊|🏋️|🏌️|🏍️|🏎️|🏏|🏐|🏑|🏒|🏓|🏔️|🏕️|🏖️|🏗️|🏘️|🏙️|🏚️|🏛️|🏜️|🏝️|🏞️|🏟️|🏠|🏡|🏢|🏣|🏤|🏥|🏦|🏧|🏨|🏩|🏪|🏫|🏬|🏭|🏮|🏯|🏰|🏳️|🏴|🏵️|🏷️|🏸|🏹|🏺|🐀|🐁|🐂|🐃|🐄|🐅|🐆|🐇|🐈|🐉|🐊|🐋|🐌|🐍|🐎|🐏|🐐|🐑|🐒|🐓|🐔|🐕|🐖|🐗|🐘|🐙|🐚|🐛|🐜|🐝|🐞|🐟|🐠|🐡|🐢|🐣|🐤|🐥|🐦|🐧|🐨|🐩|🐪|🐫|🐬|🐭|🐮|🐯|🐰|🐱|🐲|🐳|🐴|🐵|🐶|🐷|🐸|🐹|🐺|🐻|🐼|🐽|🐾|🐿️|👀|👁️|👂|👃|👄|👅|👆|👇|👈|👉|👊|👋|👌|👍|👎|👏|👐|👑|👒|👓|👔|👕|👖|👗|👘|👙|👚|👛|👜|👝|👞|👟|👠|👡|👢|👣|👤|👥|👦|👧|👨|👩|👪|👫|👬|👭|👮|👯|👰|👱|👲|👳|👴|👵|👶|👷|👸|👹|👺|👻|👼|👽|👾|👿|💀|💁|💂|💃|💄|💅|💆|💇|💈|💉|💊|💋|💌|💍|💎|💏|💐|💑|💒|💓|💔|💕|💖|💗|💘|💙|💚|💛|💜|💝|💞|💟|💠|💡|💢|💣|💤|💥|💦|💧|💨|💩|💪|💫|💬|💭|💮|💯|💰|💱|💲|💳|💴|💵|💶|💷|💸|💹|💺|💻|💼|💽|💾|💿|📀|📁|📂|📃|📄|📅|📆|📇|📈|📉|📊|📋|📌|📍|📎|📏|📐|📑|📒|📓|📔|📕|📖|📗|📘|📙|📚|📛|📜|📝|📞|📟|📠|📡|📢|📣|📤|📥|📦|📧|📨|📩|📪|📫|📬|📭|📮|📯|📰|📱|📲|📳|📴|📵|📶|📷|📸|📹|📺|📻|📼|📽️|📿|🔀|🔁|🔂|🔃|🔄|🔅|🔆|🔇|🔈|🔉|🔊|🔋|🔌|🔍|🔎|🔏|🔐|🔑|🔒|🔓|🔔|🔕|🔖|🔗|🔘|🔙|🔚|🔛|🔜|🔝|🔞|🔟|🔠|🔡|🔢|🔣|🔤|🔥|🔦|🔧|🔨|🔩|🔪|🔫|🔬|🔭|🔮|🔯|🔰|🔱|🔲|🔳|🔴|🔵|🔶|🔷|🔸|🔹|🔺|🔻|🔼|🔽|🕉️|🕊️|🕋|🕌|🕍|🕎|🕐|🕑|🕒|🕓|🕔|🕕|🕖|🕗|🕘|🕙|🕚|🕛|🕜|🕝|🕞|🕟|🕠|🕡|🕢|🕣|🕤|🕥|🕦|🕧|🕯️|🕰️|🕳️|🕴️|🕵️|🕶️|🕷️|🕸️|🕹️|🕺|🖇️|🖊️|🖋️|🖌️|🖍️|🖐️|🖕|🖖|🖤|🖥️|🖨️|🖱️|🖲️|🖼️|🗂️|🗃️|🗄️|🗑️|🗒️|🗓️|🗜️|🗝️|🗞️|🗡️|🗣️|🗨️|🗯️|🗳️|🗺️|🗻|🗼|🗽|🗾|🗿|😀|😁|😂|😃|😄|😅|😆|😇|😈|😉|😊|😋|😌|😍|😎|😏|😐|😑|😒|😓|😔|😕|😖|😗|😘|😙|😚|😛|😜|😝|😞|😟|😠|😡|😢|😣|😤|😥|😦|😧|😨|😩|😪|😫|😬|😭|😮|😯|😰|😱|😲|😳|😴|😵|😶|😷|😸|😹|😺|😻|😼|😽|😾|😿|🙀|🙁|🙂|🙃|🙄|🙅|🙆|🙇|🙈|🙉|🙊|🙋|🙌|🙍|🙎|🙏|🚀|🚁|🚂|🚃|🚄|🚅|🚆|🚇|🚈|🚉|🚊|🚋|🚌|🚍|🚎|🚏|🚐|🚑|🚒|🚓|🚔|🚕|🚖|🚗|🚘|🚙|🚚|🚛|🚜|🚝|🚞|🚟|🚠|🚡|🚢|🚣|🚤|🚥|🚦|🚧|🚨|🚩|🚪|🚫|🚬|🚭|🚮|🚯|🚰|🚱|🚲|🚳|🚴|🚵|🚶|🚷|🚸|🚹|🚺|🚻|🚼|🚽|🚾|🚿|🛀|🛁|🛂|🛃|🛄|🛅|🛋️|🛌|🛍️|🛎️|🛏️|🛐|🛑|🛒|🛕|🛠️|🛡️|🛢️|🛣️|🛤️|🛥️|🛩️|🛫|🛬|🛰️|🛳️|🛴|🛵|🛶|🛷|🛸|🛹|🛺|🟠|🟡|🟢|🟣|🟤|🟥|🟦|🟧|🟨|🟩|🟪|🟫|🤍|🤎|🤏|🤐|🤑|🤒|🤓|🤔|🤕|🤖|🤗|🤘|🤙|🤚|🤛|🤜|🤝|🤞|🤟|🤠|🤡|🤢|🤣|🤤|🤥|🤦|🤧|🤨|🤩|🤪|🤫|🤬|🤭|🤮|🤯|🤰|🤱|🤲|🤳|🤴|🤵|🤶|🤷|🤸|🤹|🤺|🤼|🤽|🤾|🤿|🥀|🥁|🥂|🥃|🥄|🥅|🥇|🥈|🥉|🥊|🥋|🥌|🥍|🥎|🥏|🥐|🥑|🥒|🥓|🥔|🥕|🥖|🥗|🥘|🥙|🥚|🥛|🥜|🥝|🥞|🥟|🥠|🥡|🥢|🥣|🥤|🥥|🥦|🥧|🥨|🥩|🥪|🥫|🥬|🥭|🥮|🥯|🥰|🥱|🥳|🥴|🥵|🥶|🥺|🥻|🥼|🥽|🥾|🥿|🦀|🦁|🦂|🦃|🦄|🦅|🦆|🦇|🦈|🦉|🦊|🦋|🦌|🦍|🦎|🦏|🦐|🦑|🦒|🦓|🦔|🦕|🦖|🦗|🦘|🦙|🦚|🦛|🦜|🦝|🦞|🦟|🦠|🦡|🦢|🦥|🦦|🦧|🦨|🦩|🦪|🦮|🦯|🦴|🦵|🦶|🦷|🦸|🦹|🦺|🦻|🦼|🦽|🦾|🦿|🧀|🧁|🧂|🧃|🧄|🧅|🧆|🧇|🧈|🧉|🧊|🧍|🧎|🧏|🧐|🧑|🧒|🧓|🧔|🧕|🧖|🧗|🧘|🧙|🧚|🧛|🧜|🧝|🧞|🧟|🧠|🧡|🧢|🧣|🧤|🧥|🧦|🧧|🧨|🧩|🧪|🧫|🧬|🧭|🧮|🧯|🧰|🧱|🧲|🧳|🧴|🧵|🧶|🧷|🧸|🧹|🧺|🧻|🧼|🧽|🧾|🧿|🩰|🩱|🩲|🩳|🩸|🩹|🩺|🪀|🪁|🪂|🪐|🪑|🪒|🪓|🪔|🪕"/>
    </restriction>
  </simpleType>
</schema>

=== consortium-chat/constitution/CONstitution.xml
<?xml version="1.0" standalone="no"?>
<?xml-stylesheet href="tome.xsl" type="text/xsl"?>
<tome
  xmlns="https://consortium.chat/tome"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://consortium.chat/tome tome.xsd"
  id="📜">
  <title>The CONstitution</title>
  <chapter id="🤔">
    <title>Preamble</title>
    <text id="🎬">We, the <toa ref="constituent">CONstituents</toa> of the CONsortium — having resolved to ensure long-lasting CONsensus of moderation, perpetuate burocracy, and formalize shenanigans — do hereby adopt and commit to upholding this <toa definition="true" ref="constitution">CONstitution</toa>.</text>
  </chapter>
  <chapter id="🎩">
    <title>The CONstituency</title>
    <text id="📖">The <toa definition="true" ref="constituent">CONstituency</toa> is the body of active voters.</text>
    <list id="📃">
      <intro>Membership in The <toa ref="constituent">CONstituency</toa> is exclusive and only includes these people:</intro>
      <item id="🐚">shelvacu#8719 (discord id 165858230327574528)</item>
      <item id="🙉">colin#7983 (discord id 125003180219170816)</item>
      <item id="🙃">metanomial#0001 (discord id 155438323354042368)</item>
      <item id="✨️">azure#3608 (discord id 182663630280589312)</item>
      <item id="💳">mstafford#7067 (discord id 373610438560317441)</item>
    </list>
    <section id="👑">
      <title>Supreme Leaders</title>
      <text id="📖"><toa definition="true" ref="supreme-leader">Supreme Leader</toa> is a title that a <toa ref="constituent">CONstituent</toa> may carry.</text>
      <list id="📃">
        <intro>The following <toa ref="constituent">CONstituents</toa> are <toa ref="supreme-leader">Supreme Leaders</toa>:</intro>
        <item id="🐚">shelvacu#8719 (discord id 165858230327574528)</item>
        <item id="🙉">colin#7983 (discord id 125003180219170816)</item>
        <item id="🙃">metanomial#0001 (discord id 155438323354042368)</item>
      </list>
      <text id="✔️"><toa ref="supreme-leader">Supreme Leaders</toa> may do anything by unanimous informal vote of all current <toa ref="supreme-leader">Supreme Leaders</toa>. This is an <toa definition="true" ref="override-vote">override vote</toa>.</text>
      <text id="❌️">A message must call for an <toa ref="override-vote">override vote</toa> somehow. A <toa ref="motion">motion</toa> in which all <toa ref="supreme-leader">Supreme Leaders</toa> have <toa ref="motion-vote">voted</toa> in favor does not trigger an <toa ref="override-vote">override vote</toa>.</text>
    </section>
  </chapter>
  <chapter id="💳">
    <title>Fungibles</title>
    <text id="📖"><toa definition="true" ref="fungible">Fungibles</toa> are indivisible units of currency — owned by <toa ref="constituent">CONstituents</toa> and/or Discord users — that may be useful for other purposes.</text>
    <list
      id="📃"
      join="and">
      <intro>The classes of <toa ref="fungible">fungibles</toa> are:</intro>
      <item id="⭐️"><toa definition="true" ref="fungible-pc">Political Capital (pc)</toa></item>
      <item id="⚡️"><toa definition="true" ref="fungible-gen">Generators (gens)</toa></item>
      <item id="💎"><toa definition="true" ref="fungible-sb">StatusBux (sb)</toa></item>
    </list>
    <text id="💥">
      <toa ref="fungible">Fungibles</toa> can not be
      <inlist join="andor">
        <item>created</item>
        <item>destroyed</item>
      </inlist>
      except as specifically authorized in
      <inlist join="andor">
        <item><toa ref="super-motion">super motions</toa></item>
        <item>this <toa ref="constitution">CONstitution</toa></item>
      </inlist>.
    </text>
    <section id="✈️">
      <title>Protection from transfer</title>
      <text id="🤗"><toa ref="fungible">Fungibles</toa> can not be transferred without the explicit consent of the current owner.</text>
      <text id="🗳️">
        Making an action to
        <inlist join="or">
          <item>cast a <toa ref="motion-vote">vote</toa></item>
          <item>create a <toa ref="motion">motion</toa> that requires <toa ref="motion-vote">votes</toa></item>
        </inlist>
        counts as explicit consent to remove the necessary <toa ref="fungible-pc">PC</toa>.
      </text>
    </section>
    <section id="♻️">
      <title>Generators</title>
      <text id="♻️">
        Every day at midnight UTC all owners of any <toa ref="fungible-gen">generators</toa> receive one <toa ref="fungible-pc">PC</toa> for each <toa ref="fungible-gen">generator</toa> they own at that moment.
      </text>
    </section>
    <section id="👤">
      <title>Privacy of fungibles</title>
      <text id="📈">The amount of <toa ref="fungible">fungibles</toa> owned by a person (their <toa definition="true" ref="fungible-balance">balances</toa>) is private, and must not be revealed without their explicit consent.</text>
      <list id="👀" join="or">
        <intro>The transactions that a person has participated in are private, and must not be revealed unless:</intro>
        <item id="🗳️">The transaction is a <toa ref="motion-vote">vote</toa> on a <toa ref="motion">motion</toa>.</item>
        <item id="📜">The transaction is creating a <toa ref="motion">motion</toa>.</item>
        <item id="👌">At least one party has given explicit consent.</item>
      </list>
      <text id="👁️">
        The protections in this section shall not be construed to
        <inlist join="or">
          <item>prohibit</item>
          <item>restrict</item>
        </inlist>
        the public
        <inlist join="or">
          <item>transfer</item>
          <item>fabrication</item>
          <item>destruction</item>
        </inlist>
        of <toa ref="fungible">fungibles</toa>, even if such may in effect reveal details about a person's
        <inlist join="or">
          <item><toa ref="fungible-balance">balances</toa></item>
          <item>transactions</item>
        </inlist>.
      </text>
    </section>
  </chapter>
  <chapter id="📜">
    <title>Motions</title>
    <list id="🤔" join="or">
      <intro>A <toa definition="true" ref="motion">motion</toa> is a proposed action to be taken by the CONsortium as an entity in theory, and once passed allows members to take action to implement it in practice. This includes but is not limited to:</intro>
      <item id="⚙️">Making changes to the discord server</item>
      <item id="💸">
        <inlist join="andor">
          <item>Fabricating</item>
          <item>transferring</item>
          <item>destroying</item>
        </inlist>
        <toa ref="fungible">fungibles</toa>
      </item>
      <item id="🗣️">Declarations</item>
      <item id="📋">Adopting administrative procedures</item>
      <item id="📝">Amending tomes, including The CONstitution</item>
    </list>
    <text id="🔢">A <toa ref="motion">motion</toa> is first <toa definition="true" ref="motion-propose">proposed</toa>, after which it is <toa definition="true" ref="motion-state-pending">pending</toa> during which it can be voted on, then possibly <toa definition="true" ref="motion-pass">passed</toa>. A <toa ref="motion">motion</toa> can not have any effect before it is <toa ref="motion-pass">passed</toa>.</text>
    <list join="and" id="2️⃣">
      <intro>There are two kinds of <toa ref="motion">motions</toa>:</intro>
      <item id="👶"><toa definition="true" ref="motion-simple">Simple motions</toa></item>
      <item id="💥"><toa definition="true" ref="motion-super">Super motions</toa></item>
    </list>
    <section id="👶">
      <title>Simple motions</title>
      <text id="👐"><toa ref="motion-simple">Simple motions</toa> require more than half of the <toa ref="motion-vote">votes</toa> on the <toa ref="motion">motion</toa> to be in favor to <toa ref="motion-pass">pass</toa>.</text>
      <text id="👶"><toa ref="motion-simple">Simple motions</toa> are limited in that they are less powerful than the <toa ref="constitution">CONstitution</toa>.</text>
      <text id="🚫">
        <toa ref="motion-simple">Simple motions</toa> cannot
        <inlist join="or">
          <item>amend</item>
          <item>override</item>
        </inlist>
        the <toa ref="constitution">CONstitution</toa>.
      </text>
    </section>
    <section id="💥">
      <title>Super motions</title>
      <text id="🌊"><toa ref="motion-super">Super motions</toa> require more than two-thirds of the <toa ref="motion-vote">votes</toa> on the <toa ref="motion">motion</toa> to be in favor to <toa ref="motion-pass">pass</toa>.</text>
      <text id="🌟"><toa ref="motion-super">Super motions</toa> are not at all limited. <toa ref="motion-super">Super motions</toa> can do anything once passed, including but not limited to amending or overriding the CONstitution.</text>
    </section>
    <section id="🗣️">
      <title>Calling motions</title>
      <text id="👽">All <toa ref="constituent">CONstituents</toa> have the inalienable right to <toa ref="motion-propose">call motions</toa> if they have enough <toa ref="fungible-pc">pc</toa> to do so and have not exceeded their daily limit.</text>
      <text id="❔️">Each CONstituent is limited to <toa ref="motion-propose">proposing</toa> 10 <toa ref="motion">motions</toa> (no matter which kind) per UTC day.</text>
      <text id="👶">To call a <toa ref="motion-simple">simple motion</toa>, a <toa ref="constituent">CONstituent</toa> must have enough <toa ref="fungible-pc">PC</toa> to <toa ref="motion-vote">vote</toa> for that <toa ref="motion">motion</toa> at least **once**. When called, they do and must <toa ref="motion-vote">vote</toa> for that <toa ref="motion">motion</toa> at least **once**.</text>
